-- CURRENT_DATE / CURDATE
SELECT CURRENT_DATE();
SELECT CURDATE();

-- CURRENT_TIME / CURTIME
SELECT CURRENT_TIME();
SELECT CURTIME();

-- NOW / CURRENT_TIMESTAMP
SELECT NOW();
SELECT CURRENT_TIMESTAMP();

-- DATE
SELECT DATE('2026-02-28');

-- TIME
SELECT TIME('2026-05-28 15:45:00');

-- YEAR / MONTH / DAY
SELECT YEAR(NOW());
SELECT MONTH(NOW());
SELECT DAY(NOW());

-- DAYNAME / MONTHNAME
SELECT DAYNAME(NOW());
SELECT MONTHNAME(NOW());

-- DATE_ADD / ADDDATE
SELECT DATE_ADD(NOW(), INTERVAL 10 DAY);
SELECT ADDDATE(NOW(), INTERVAL 2 MONTH);

-- DATE_SUB
SELECT DATE_SUB(NOW(), INTERVAL 7 DAY);

-- DATEDIFF
SELECT DATEDIFF(NOW(), '2005-09-20');

-- TIMEDIFF
SELECT TIMEDIFF('10:30:00', '10:35:12');

-- STR_TO_DATE
SELECT STR_TO_DATE('2005-09-20', '%Y-%m-%d');

-- DATE_FORMAT
SELECT DATE_FORMAT('2025-09-23', '%W %M %Y')

